# Generated by Django 3.2.4 on 2021-07-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20210707_1651'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurso')),
            ],
        ),
    ]
