# Generated by Django 3.2.4 on 2021-07-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20210707_1651'),
        ('home', '0002_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='recurso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurso'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
        ),
    ]
